### ISSUE TITLE
Listener error aborts further listener executions

### ISSUE THREAD

**Issue by frenchroasted** [jeffrose/emitter#1]
The listeners execute their callbacks in a for loop with no error trapping. If one of the callbacks throws an error, this will halt the for loop and other listeners in the collection will never execute. It might be nice to trap and collect callback errors in order to allow other callbacks to run, and possibly re-throw them at the end of the loop.

**Comment by jeffrose** [comment]
That's not a bad idea. I would be inclined to `emit( 'error' )`, which if it has no listeners throws an error.
